### ISSUE TITLE
dialog: Dark theme for dialog

### ISSUE THREAD

**Issue by js-park92** [pluralsight/classic-design-system#2073]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

## Description
Currently, dialog is only available in light theme.

https://github.com/pluralsight/design-system/blob/08e74398e9c8543d98610380cb209fdbaa1f862a/packages/dialog/src/react/index.tsx#L126

## Suggestion
I believe following code changes would allow dark theme to be used.

```ts
import Theme, { useTheme } from '@pluralsight/ps-design-system-theme'
...
const theme = useTheme();
...
<Theme name={theme}>
...
```

With following className added to the `psds-dialog` as well as `psds-dialog__content` and adding appropriate background colors to `index.css` would apply correct colors for both dark and light theme.

```ts
`psds-theme--${theme}`
```

```css
.psds-dialog.psds-theme--light {
  background: var(--ps-colors-white);
}
.psds-dialog.psds-theme--dark {
  background: var(--ps-colors-background-dark-2);
}
.psds-dialog__content.psds-theme--light {
  color: var(--ps-colors-text-icon-high-on-light);
}
.psds-dialog__content.psds-theme--drak {
  color: var(--ps-colors-text-icon-high-on-dark);
}
```

Using PSDS icon for the close button should automatically apply the theme as well.

## Screenshot

<img width="396" alt="Screen Shot 2022-01-27 at 3 33 58 PM" src="https://user-images.githubusercontent.com/42661520/151454713-d869f530-296e-4787-bb82-aacd77863262.png">

This is how it would look if the dark theme was applied to dialog.

### Motivation 🔦

Content Tooling team is trying to develop a new frontend Craft (formerly known as Cloud Craft) with PSDS and have accessible design with both light and dark theme.
